"""
Cryptographic pattern definitions.
Each pattern: id, algorithm, category, regex, quantum_risk, severity.
See docs/Rules.md for the required fields on every entry.
"""

PATTERNS = [
    {
        "id": "RSA-001",
        "algorithm": "RSA",
        "category": "asymmetric",
        "regex": r"(rsa\.generate_private_key|RSA\.generate|Cipher\.getInstance\([\"']RSA)",
        "quantum_risk": "VULNERABLE",
        "severity": "critical",
    },
    {
        "id": "ECDSA-001",
        "algorithm": "ECDSA",
        "category": "asymmetric",
        "regex": r"(ec\.generate_private_key|ECDSA|Signature\.getInstance\([\"']SHA256withECDSA)",
        "quantum_risk": "VULNERABLE",
        "severity": "critical",
    },
    {
        "id": "DH-001",
        "algorithm": "Diffie-Hellman",
        "category": "asymmetric",
        "regex": r"(dh\.generate_parameters|DiffieHellman|KeyAgreement\.getInstance\([\"']DH)",
        "quantum_risk": "VULNERABLE",
        "severity": "critical",
    },
    {
        "id": "AES-001",
        "algorithm": "AES",
        "category": "symmetric",
        "regex": r"(AES\.new|Cipher\.getInstance\([\"']AES|aes_gcm|createCipheriv\([\"']aes)",
        "quantum_risk": "PARTIAL",
        "severity": "medium",
    },
    {
        "id": "DES-001",
        "algorithm": "DES",
        "category": "symmetric",
        "regex": r"(DES\.new|Cipher\.getInstance\([\"']DES|createCipheriv\([\"']des)",
        "quantum_risk": "VULNERABLE",
        "severity": "high",
    },
    {
        "id": "3DES-001",
        "algorithm": "3DES",
        "category": "symmetric",
        "regex": r"(DES3|TripleDES|des-ede3)",
        "quantum_risk": "VULNERABLE",
        "severity": "high",
    },
    {
        "id": "CHACHA20-001",
        "algorithm": "ChaCha20",
        "category": "symmetric",
        "regex": r"(ChaCha20|chacha20_poly1305)",
        "quantum_risk": "PARTIAL",
        "severity": "low",
    },
    {
        "id": "MD5-001",
        "algorithm": "MD5",
        "category": "hash",
        "regex": r"(hashlib\.md5|MessageDigest\.getInstance\([\"']MD5|crypto\.createHash\([\"']md5)",
        "quantum_risk": "VULNERABLE",
        "severity": "high",
    },
    {
        "id": "SHA1-001",
        "algorithm": "SHA-1",
        "category": "hash",
        "regex": r"(hashlib\.sha1|MessageDigest\.getInstance\([\"']SHA-1|crypto\.createHash\([\"']sha1)",
        "quantum_risk": "VULNERABLE",
        "severity": "high",
    },
    {
        "id": "SHA256-001",
        "algorithm": "SHA-256",
        "category": "hash",
        "regex": r"(hashlib\.sha256|MessageDigest\.getInstance\([\"']SHA-256|crypto\.createHash\([\"']sha256)",
        "quantum_risk": "PARTIAL",
        "severity": "info",
    },
    {
        "id": "SHA3-001",
        "algorithm": "SHA-3",
        "category": "hash",
        "regex": r"(hashlib\.sha3|SHA3-256|SHA3-512)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "HMAC-001",
        "algorithm": "HMAC",
        "category": "mac",
        "regex": r"(hmac\.new|Mac\.getInstance\([\"']Hmac|createHmac)",
        "quantum_risk": "PARTIAL",
        "severity": "info",
    },
    {
        "id": "PBKDF2-001",
        "algorithm": "PBKDF2",
        "category": "kdf",
        "regex": r"(PBKDF2|pbkdf2_hmac)",
        "quantum_risk": "PARTIAL",
        "severity": "low",
    },
    {
        "id": "BCRYPT-001",
        "algorithm": "bcrypt",
        "category": "kdf",
        "regex": r"(bcrypt\.hashpw|bcrypt\.gensalt|BCrypt\.hashpw)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "ARGON2-001",
        "algorithm": "Argon2",
        "category": "kdf",
        "regex": r"(argon2|Argon2id)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "MLKEM-001",
        "algorithm": "ML-KEM",
        "category": "asymmetric",
        "regex": r"(ML-KEM|Kyber512|Kyber768|Kyber1024|mlkem)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "MLDSA-001",
        "algorithm": "ML-DSA",
        "category": "asymmetric",
        "regex": r"(ML-DSA|Dilithium2|Dilithium3|Dilithium5|mldsa)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "SLHDSA-001",
        "algorithm": "SLH-DSA",
        "category": "asymmetric",
        "regex": r"(SLH-DSA|SPHINCS\+|slhdsa)",
        "quantum_risk": "SAFE",
        "severity": "info",
    },
    {
        "id": "CERT-001",
        "algorithm": "X.509 Certificate",
        "category": "certificate",
        "regex": r"(-----BEGIN CERTIFICATE-----|X509Certificate|CertificateFactory\.getInstance\([\"']X\.509)",
        "quantum_risk": "VULNERABLE",
        "severity": "medium",
    },
    {
        "id": "TLS-001",
        "algorithm": "TLS 1.2",
        "category": "protocol",
        "regex": r"(TLSv1\.2|SSLv3|TLSv1\.0|TLSv1\.1)",
        "quantum_risk": "VULNERABLE",
        "severity": "high",
    },
]
